### ISSUE TITLE
Auto-Uploading of Photos from iPhone 6s Results in Corrupted Files

### ISSUE THREAD

**Issue by kevinscholz** [haiwen/seafile-iOS#154]
After uploading photos from my iPhone (v.2.5.7) into an encrypted library, some (~30%) of these pictures cannot be opened, neither via Sync Client on Mac nor via Web GUI (server v. 6.0.7)

The script to check for corrupted libraries on the server runs without errors and considers all libraries as ok. How could I further debug? Thanks a lot in advance!

<img width="467" alt="macos-error" src="https://cloud.githubusercontent.com/assets/2557501/24122833/aebc2c82-0dbd-11e7-805d-f9382e8f55a1.png">

<img width="288" alt="web-gui-error" src="https://cloud.githubusercontent.com/assets/2557501/24122834/aebd5f30-0dbd-11e7-9a3b-3509bae49de8.png">

![web-request](https://cloud.githubusercontent.com/assets/2557501/24122878/d3ac0ec2-0dbd-11e7-897c-013eb82cfe9e.jpg)

**Comment by sentientnebula** [comment]
I'm having the same issue.  Photos uploaded from iphone that are > 2.0MB all get corrupted.  Photos <= 2.0MB always transfer OK.  The problem persists in 6.1.0 Pro beta.

**Comment by freeplant** [comment]
This seems to be a server side bug we fixed a few months ago. I can't reproduce the problem with pro version 6.1.1, with either encrypted libraries or normal libraries.

**Comment by sentientnebula** [comment]
Well, I just upgraded from Pro 6.1.0 beta to Pro 6.1.1 and still have the same issue.  Photos < 2MB sync normally, but photos > ~2MB are corrupted and unreadable.  Everything else is working as it should.

**Comment by poetwang** [comment]
@sentientnebula I can not reproduce it. Could you please try seacloud.cc to see if the issue still exists?

**Comment by sentientnebula** [comment]
I created an encrypted folder on the seacloud.cc demo account and was able to manually upload any size photo from my iphone to that folder via browser interface.  I can also MANUALLY upload any size photo from my iphone to my own seafile server via web browser.   The corruption occurs on photos larger than ~2mb with  autosync.  I tried to add the test folder I created on seacloud.cc/demo to the IOS client, but it wouldn't let me add an account without a password, and as far as I know, the demo site works without a password.  Let me know how I should proceed.  Thanks.

**Comment by cookiekiller** [comment]
This is still a thing in the latest version. Any know fix?

**Comment by cookiekiller** [comment]
I can fully reproduce the issue as explained by @sentientnebula 

The issue must be caused by the autoupload function of the ios app. It's not an server issue and persisted even after switching to the pro edition.

**Comment by BernieO** [comment]
I have the same problem with community edition 6.1.2 and iOS seafile-app 2.6.6.
I don't use auto-upload. The problem occurs when manually uploading single photos bigger than  ~2MB to an encrypted library.
I did uninstall the iOS app and reinstall it, which solved the issue for a little while. But now the problem is back...

**Comment by Ultra2D** [comment]
The same thing is happening with files auto-uploaded from my iPhone SE to CE 6.2.2, SF app 2.6.8, iOS 11.1. A file of 2059761 bytes is still ok, and one of 2111016 is not.

**Comment by freeplant** [comment]
@cookiekiller @BernieO We are going to reproduce the problem and solve it in this week. Can you share such a kind of broken file with me?

**Comment by cookiekiller** [comment]
Any > 2 MB file

**Comment by BernieO** [comment]
I am sorry I can‘t provide any files right now. Currently I am not able to upload a single picture with newest Seafile app and CE 6.2.2. Maybe it has to do with my setup. But I don‘t have time to investigate right now. Sorry.

**Comment by BernieO** [comment]
There was a self-healing process going on with my server: everything is working again.

So here we go: in the attached zip-file you will find three jpg files:

- the original file (original.jpg)
- uploaded to an unencrypted library (unencrypted-Library.jpg):
slightly smaller filesize but not corrupt.
- uploaded to an encrypted library (encrypted-Library.jpg):
corrupt jpg file

I used Seafile iOS app 2.6.9 and Seafile Server CE 6.2.2

[photos.zip](https://github.com/haiwen/seafile-iOS/files/1459565/photos.zip)

**Comment by BernieO** [comment]
Looks like the latest version of the Seafile iOS app (version 2.6.10, released November 14th) has solved the problem for me.

Thanks a lot!!

**Comment by Ultra2D** [comment]
With 2.6.10 all new uploads were corrupted somehow. A Windows client could not decrypt (some/all) blocks, so it did not even download any new files successfully. Restarting my iPhone did not help. After logging off and clearing the library password on the iOS app, logging on and entering the password for the encrypted library, everything started working again including files larger than ~2MB.

**Comment by cookiekiller** [comment]
Is it now fixed or not? @poetwang

**Comment by poetwang** [comment]
It is fixed in 2.6.10
