### ISSUE TITLE
Bug report: Application freezes when uploading photos (auto-upload)

### ISSUE THREAD

**Issue by nassimosaz** [haiwen/seafile-iOS#196]
I’m using SeafilePro on my linux server, my iOS client was fully functional until after I updated to the last version.. when I try to upload photos, the process freezes after few seconds of uploading.
You can further see that in this video which I captured: https://goo.gl/wVST83

**Comment by nassimosaz** [comment]
My device info: 
iPhone 7 Plus 128gb
iOS version: 11.1.2
SeafilePro iOS client version: 2.6.10

**Comment by nassimosaz** [comment]
(I’m not using any encrypted libraries on my server)

**Comment by vectr0n** [comment]
I am also seeing this behavior. Running Seafile Pro 6.2.1 with Seafile Pro iOS App 2.6.10 on an iPhone 7 128GB with iOS version 11.2. Recently switched back to an iPhone and have really noticed the lack of effort on the iOS App when compared to Android.

**Comment by vectr0n** [comment]
Any idea when this will be fixed? The app freezes when you open it and does not actually upload anything making the whole app useless.

**Comment by Admonstrator** [comment]
@vectr0n It's the same issue like this one:
https://github.com/haiwen/seafile-iOS/issues/194
https://github.com/haiwen/seafile-iOS/issues/192

I saw that there was an patch so maybe they will build a new version soon.

**Comment by vectr0n** [comment]
@Admonstrator at this point it’s easier to switch to a solution that has working mobile apps. This is not a good look for Seafile to have an absolutely useless iOS app. Specially when there is sooooo many iOS users who can’t upload anything automatically to seafile. Users shouldn’t have to jump thru hoops to use basic features.

**Comment by Admonstrator** [comment]
@vectr0n There is no good alternative to Seafile right now.
NextCloud does not support library based encryption. I don't know any other app who does support it.

The useless iOS app should be fine as soon as the patch arrived.

**Comment by vectr0n** [comment]
@Admonstrator I do not make use of the encrypted libraries in Seafile, the whole drive is encrypted, so there are other solutions that have working mobile apps I can check out, and will be quicker then waiting for the dev to fix the actual issue seeing as its been referenced in many issues and it's taking way to long to fix.

**Comment by Admonstrator** [comment]
@vectr0n In that case you should look into NextCloud. It was my storage provide before I moved to Seafile.

**Comment by nassimosaz** [comment]
@Admonstrator Even on your last update, the bug is still not fixed!! The app freezes after uploading 5 or 6 photos. Please identify the issues. Thanks!

**Comment by Admonstrator** [comment]
@nassimosaz
I am afraid but I am only a user. Just like you. 
So no way to fix this issue.

**Comment by freeplant** [comment]
The problem should have been fixed in the latest version.

**Comment by bigfatfox** [comment]
I cannot confirm.
The issue persists with iphone 8 and any combination of versions

iOS 11.2, 11.4
seafile server 6.2.5, 6.3.0 beta
seafile pro 2.7.7
