### ISSUE TITLE
Seafile FotoView is very slow

### ISSUE THREAD

**Issue by confile** [haiwen/seafile-iOS#86]
It would be great to have an option that photos could be pre loaded such that you do not have to wait for every photo when you want to browse through a list of them.

**Comment by poetwang** [comment]
Now when you open a photo, the next photo in the same folder will be loaded in background, maybe preload more photos is a better choice.

**Comment by confile** [comment]
Yes it would be a better choice to preload more photos. Could you please do that.

Also preview images might be presented like in this viewer: https://github.com/mwaterfall/MWPhotoBrowser

@poetwang Do you think you could include it in the seafile ios client. That would make it great to look at photos. Since I guess photos is the number one thing to do when using mobile seafile on iPhone.

**Comment by MartinBusch** [comment]
@confile great idea. I want that feature too. @poetwang this might not be hard to include for you?

**Comment by steffimueller** [comment]
+1

**Comment by poetwang** [comment]
Will  be added in the next version

**Comment by confile** [comment]
That is Great thank you. I look forward to test it.

**Comment by confile** [comment]
@poetwang Does v.2.1.1. contains this feature?

**Comment by poetwang** [comment]
yes

**Comment by poetwang** [comment]
fixed in v2.1.1

**Comment by confile** [comment]
@poetwang I still do not see this feature: https://github.com/mwaterfall/MWPhotoBrowser

I use ios7 is it only available in ios8?
