### ISSUE TITLE
Deleting cache and downloading again

### ISSUE THREAD

**Issue by hoba87** [haiwen/seafile-iOS#94]
When deleting the cache, I am able to download files (that were downloaded before) again only after exiting the app and starting the app again.

**Comment by poetwang** [comment]
will be fixed in the next version.

**Comment by poetwang** [comment]
fixed

**Comment by stuntsman** [comment]
I'm still experiencing this behavior with v2.5.7 on iOS 10.2.1. Before restarting the app I've got an error message "Can't download file" without any
further info.
